In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("labtest 1.csv")

In [3]:
df.head(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,101,6.3,3.3,6.0,2.5,Iris-virginica
1,102,5.8,2.7,5.1,0.0,Iris-virginica
2,103,7.1,3.0,5.9,2.1,Iris-virginica
3,104,6.3,2.9,5.6,1.8,Iris-virginica
4,105,6.5,3.0,5.8,2.2,Iris-virginica
5,106,7.6,3.0,6.6,2.1,Iris-virginica
6,107,4.9,2.5,4.5,1.7,Iris-virginica
7,108,7.3,2.9,6.3,1.8,Iris-virginica
8,109,6.7,2.5,5.8,0.0,Iris-virginica
9,110,7.2,3.6,6.1,2.5,Iris-virginica

In [4]:
df.tail(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
40,141,6.7,3.1,5.6,2.4,Iris-virginica
41,142,6.9,3.1,5.1,2.3,Iris-virginica
42,143,5.8,2.7,5.1,1.9,Iris-virginica
43,144,6.8,3.2,5.9,2.3,Iris-virginica
44,145,6.7,3.3,5.7,2.5,Iris-virginica
45,146,6.7,3.0,5.2,2.3,Iris-virginica
46,147,6.3,2.5,5.0,1.9,Iris-virginica
47,148,6.5,3.0,5.2,2.0,Iris-virginica
48,149,6.2,3.4,5.4,2.3,Iris-virginica
49,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
print(df.columns)

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [6]:
print(df.dtypes)

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [8]:
df['PetalWidthCm'] = df['PetalWidthCm'].replace(0.0, nan)

NameError: name 'nan' is not defined

In [9]:
df[cols] = df[cols].replace({'0.0':Nan})

NameError: name 'cols' is not defined